Enable subpath for S3 bucket (#58)
* Enable subpath for S3 bucket

* Enable subpath for S3 bucket

* Add slash to paths

* Slash is not needed in the input

* Add base path for slidev

* fix ci for nextjs

* Filter for nextjs

* Fix pipeline, return true if not exist

* Fix pipeline

* hotfix pipeline

* Remove out from slidev

diff --git a/.github/workflows/nextjs-ci.yaml b/.github/workflows/nextjs-ci.yaml
--- a/.github/workflows/nextjs-ci.yaml
+++ b/.github/workflows/nextjs-ci.yaml
@@ -19,6 +19,11 @@ on:
         required: false
         type: string
         default: eu-central-1
+      base-path:
+        required: false
+        type: string
+        default: ''
+
 
 jobs:
   build:
@@ -34,12 +39,55 @@ jobs:
         with:
           node-version: '22'
 
+      - name: Setup subpath
+        if: ${{ inputs.base-path != '' }}
+        working-directory: ${{ inputs.path }}
+        run: |
+          rm next.config.mjs || true
+          cat << 'EOF' > next.config.mjs
+            import nextra from 'nextra'
+            
+            /**
+            * @type {import('next').NextConfig}
+            */
+            const nextConfig = {
+              basePath: '/${{ inputs.base-path }}',
+              output: 'export',
+              images: {
+                unoptimized: true // mandatory, otherwise won't export
+              }
+            }
+            const withNextra = nextra({
+              // ... other Nextra config options
+            })
+
+            export default withNextra(nextConfig)
+          EOF
+
       - name: Install dependencies
         run: npm install
         working-directory: ${{ inputs.path }}
+      
+      - name: Search for Slidev in package.json
+        id: slidev
+        working-directory: ${{ inputs.path }}
+        run: |
+          if grep -q '"slidev"' package.json; then
+            echo "Slidev found, enable variable slidev=true"
+            echo "slidev=true" >> $GITHUB_OUTPUT
+          else
+            echo "Slidev not found"
+          fi
 
       - name: Build the Next.js site
-        run: npm run build
+        run: |
+          if [ "${{ steps.slidev.outputs.slidev }}" = "true" ]; then
+            echo "Building Slidev presentation"
+            npm run build -- --base=/${{ inputs.base-path }} 
+          else
+            echo "Building Next.js site"
+            npm run build
+          fi
         working-directory: ${{ inputs.path }}
 
       - name: Upload build artifacts
@@ -68,7 +116,7 @@ jobs:
 
       - name: Deploy to S3
         run: |
-          aws s3 sync . s3://${{ inputs.s3-bucket }} --delete --acl public-read
+          aws s3 sync . s3://${{ inputs.s3-bucket }}/${{ inputs.base-path }} --delete --acl public-read
         env:
           AWS_REGION: ${{ inputs.aws-region }}
 
@@ -78,7 +126,7 @@ jobs:
 
       - name: Echo URL
         id: echo_url
-        run: echo S3_URL=http://${{ inputs.s3-bucket }}.s3-website.${{ inputs.aws-region }}.amazonaws.com >> $GITHUB_OUTPUT
+        run: echo S3_URL=http://${{ inputs.s3-bucket }}.s3-website.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.base-path }} >> $GITHUB_OUTPUT
       
       - name: Print as comment
         if: ${{ github.event_name == 'pull_request' }}
