Test slidev pages with github pages

diff --git a/.github/workflows/nextjs-pages.yaml b/.github/workflows/nextjs-pages.yaml
--- a/.github/workflows/nextjs-pages.yaml
+++ b/.github/workflows/nextjs-pages.yaml
@@ -27,7 +27,7 @@ jobs:
       - name: Setup Pages
         working-directory: ${{ inputs.path }}
         run: |
-          rm next.config.mjs
+          rm next.config.mjs || true
           cat << 'EOF' > next.config.mjs
             import nextra from 'nextra'
             
@@ -54,6 +54,28 @@ jobs:
 
       - name: Install dependencies
         run: npm install
+        working-directory: ${{ inputs.path }}
+
+      - name: Search for Slidev in package.json
+        id: slidev
+        working-directory: ${{ inputs.path }}
+        run: |
+          if grep -q '"slidev"' package.json; then
+            echo "Slidev found, enable variable slidev=true"
+            echo "slidev=true" >> $GITHUB_OUTPUT
+          else
+            echo "Slidev not found"
+          fi
+
+      - name: Build the Next.js site
+        run: |
+          if [ "${{ steps.slidev.outputs.slidev }}" = "true" ]; then
+            echo "Building Slidev presentation"
+            npm run build -- --base=/${{ github.event.repository.name }}
+          else
+            echo "Building Next.js site"
+            npm run build
+          fi
         working-directory: ${{ inputs.path }}
 
       - name: Build the Next.js site
